accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('', views.dashboard, name='dashboardd'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<str:user_name>/<int:order_id>/', views.order_detail, name='order_detail'),

    path('forget_password/', views.forget_password, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('reset_password/', views.reset_password, name="reset_password"),
]

cart/urls.py
from django import urls
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin-honeypot')),
    path('adminlogin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/alerts.html
{% if messages %}

    {% for message in messages %}
    <div style="font-size:18px;font-weight:500;" id="message" class="container text-center">
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}{% endif %}
        {{ message }}
    </div>
    </div>
    {% endfor %}

{% endif %}

templates/includes/dashboard_slider.html
<div class="col-12 col-md-3 ">
    <div class="listdashboard list-group ">

		<a class="list-group-item {% if '/dashboard/' in request.path  %}active{% endif %}" href="{% url 'accounts:dashboard' %}" 
        {% if '/dashboard/' in request.path  %}style="background:#FD7E14;border:1px solid #FD7E14;color:#2B0D0D"{% endif %}"> Dashboard </a>

		<a class="list-group-item {% if '/my_orders/' in request.path %}active{% endif %}" href="{% url 'accounts:my_orders' %}" 
        {% if '/my_orders/' in request.path %}style="background:#FD7E14;border:1px solid #FD7E14;color:#2B0D0D"{% endif %}> My Orders </a>

        
		<a class="list-group-item {% if '/edit_profile/' in request.path  %}active{% endif %}" href="{% url 'accounts:edit_profile' %}" 
        {% if '/edit_profile/' in request.path  %}style="background:#FD7E14;border:1px solid #FD7E14;color:#2B0D0D"{% endif %}>Profile</a>

        <a class="list-group-item {% if '/change_password/' in request.path  %}active{% endif %}" href="{% url 'accounts:change_password' %}"
        {% if '/change_password/' in request.path  %}style="background:#FD7E14;border:1px solid #FD7E14;color:#2B0D0D"{% endif %}>Change Password</a>
        
    </div>
    <br>
    <ul class="listdashboardlogout list-group text-center">
        <a href="{% url "accounts:logout" %}"><li class="list-group-item"><i class="fa fa-power-off"></i> Logout</li></a>
    </ul>
</div>