accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('', views.dashboard, name='dashboardd'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<str:user_name>/<int:order_id>/', views.order_detail, name='order_detail'),

    path('forget_password/', views.forget_password, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('reset_password/', views.reset_password, name="reset_password"),
]

cart/urls.py
from django import urls
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin-honeypot')),
    path('adminlogin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='categries'),
    path('category/<slug:category_slug>/<slug:product_details_slug>/', views.product_details, name='product_details'),
    path('search/', views.search, name='search'),
    path('review/<int:product_id>/', views.review, name='review'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>{% block title %}Forever - Your Favorite Shop Forever{% endblock %}</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'img/core-img/logo1.png' %}">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static 'css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    
    <script src="https://www.paypal.com/sdk/js?client-id=Af-__bvaB6GK0K8O7fQTv-AlntbdYqnAeoOhhiZW555_6vgDO67Hlu7kR7w8gKbL6U7vVaVwcFmzjaMA&currency=USD"></script>

</head>

<body>

    <!-- ##### Header Area Start ##### -->
    <header class="header_area">
        <div class="classy-nav-container breakpoint-off d-flex align-items-center justify-content-between">
            <!-- Classy Menu -->
            <nav class="classy-navbar" id="essenceNav">
                <!-- Logo -->
                <a class="nav-brand" href="\">FOREVER</a>
                <!-- Navbar Toggler -->
                <div class="classy-navbar-toggler">
                    <span class="navbarToggler"><span></span><span></span><span></span></span>
                </div>
                <!-- Menu -->
                <div class="classy-menu">
                    <!-- close btn -->
                    <div class="classycloseIcon">
                        <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                    </div>
                    <!-- Nav Start -->
                    <div class="classynav">
                        <ul>
                            <li><a href="/store">Store</a>
                                
                            </li>
                            <li><a href="{% url 'store:store' %}">Categories <i class="fas fa-arrow-down"></i></a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'store:store' %}">All Products</a></li>
                                    {% for category in categories %}
                                        <li><a href="{{ category.get_category_slug_url }}">{{category.name}}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <!--
                            <li><a href="static/blog.html">Blog</a></li>
                            <li><a href="static/contact.html">Contact</a></li>
                            -->
                        </ul>
                    </div>
                    <!-- Nav End -->
                </div>
            </nav>

            <!-- Header Meta Data -->
            <div class="header-meta d-flex clearfix justify-content-end">
                <!-- Search Area -->
                <div class="search-area">
                    <form action="{% url 'store:search' %}" method="GET">
                        <input type="search" name="keyword" id="headerSearch" placeholder="Type for search">
                        <button style="background:#FD7E14;color:#1B0606;padding:5px; border-radius:3px ;margin-left:-25px;width:40px" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                    </form>
                </div>
                <div class="cart-area">
                    <a  href="{% url 'cart:cart' %}" id="essenceCartBtn"><i class="fas fa-shopping-cart"></i><span>{{cart_count}}</span></a>
                </div>
                {% if user.id is None %}
                <!-- Favourite Area -->
                <div class="favourite-area">
                    <a style="color:#FD7E14;font-weight: 600" href="{% url 'accounts:login' %}">Log in</a>
                </div>


                <div class="user-login-info singbotton">
                    <a href="{% url 'accounts:register' %}"><div class="btn" >Sign up</div></a>
                </div>
                
                <!-- User Login Info 
                <div class="user-login-info">
                    <a href="static/#"><i class="fas fa-user"></i></a>
                </div>
                -->
                {% else %}
                

                <div class="user-login-infooo">
                    <a class="profilebotton" href="{% url 'accounts:dashboard' %}">
                    <img class="rounded-circle" src="{{ userr.profile_picture.url }}" alt="user-image" >
                    &nbsp;
                    {{user.full_name | capfirst}}
                    </a>
                </div>
                {% endif %}
                
                

                    
                <!-- Cart Area -->
                
            </div>
            
        </div>
    </header>
    <!-- ##### Header Area End ##### -->
    
    <!-- ##### Right Side Cart Area ##### -->
    <div class="cart-bg-overlay"></div>
    {% block content %}

    {% endblock %}
    
    <div class="footer-basic">
        <footer>
            <div class="social">
            <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></i></a>
            <a href="https://www.snapchat.com/"><i class="fab fa-snapchat-ghost"></i></a>
            <a href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
            <a href="https://facebook.com/"><i class="fab fa-facebook-f"></i></a>
            </div>
            <p class="copyright">Copyright@2021 | by Omar Reda</p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    <!-- ##### Footer Area End ##### -->

    <!-- jQuery (Necessary for All JavaScript Plugins) -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Classy Nav js -->
    <script src="{% static 'js/classy-nav.min.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>

</body>

</html>