cart/urls.py
from django import urls
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin-honeypot')),
    path('adminlogin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name="home"),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('place_order/', views.place_order, name='place_order'),
    path('payments/', views.payments, name='payments'),
    path('order_completed/', views.order_completed, name='order_complete'),
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='categries'),
    path('category/<slug:category_slug>/<slug:product_details_slug>/', views.product_details, name='product_details'),
    path('search/', views.search, name='search'),
    path('review/<int:product_id>/', views.review, name='review'),
]

cart/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account

# from shop.models import Variation
# from accounts.models import Account

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product
    

home/models.py
from django.db import models
from store.models import Category
from django.urls import reverse

class Popular_Products(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=300, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    discount = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    image = models.ImageField(upload_to='photos/products')
    image_havor = models.ImageField(upload_to='photos/products-havor')
    stock = models.IntegerField()
    new = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)
    

    date_joined_for_format = models.DateTimeField(auto_now_add=True)
    last_login_for_format = models.DateTimeField(auto_now=True)
    def created(self):
        return self.date_joined_for_format.strftime('%B %d %Y')
    def updated(self):
        return self.last_login_for_format.strftime('%B %d %Y')

    def __str__(self):
        return self.name
    
    #def averageRating(self):
    #    reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
    #    avg = 0
    #    if reviews['average'] is not None:
    #        avg = float(reviews['average'])
    #    return avg
    #
    #def countReview(self):
    #    reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
    #    count = 0
    #    if reviews['count'] is not None:
    #        count = int(reviews['count'])
    #    return count
#
    def get_prodcut_details_url(self):
        return reverse('store:product_details', args=[self.category.slug, self.slug])
    
    #class Meta:
    #    verbose_name_plural = 'Products'
    #    ordering = ('-date_joined_for_format',)
    


class For_You(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=300, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    discount = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    image = models.ImageField(upload_to='photos/products')
    image_havor = models.ImageField(upload_to='photos/products-havor')
    stock = models.IntegerField()
    new = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)

    date_joined_for_format = models.DateTimeField(auto_now_add=True)
    last_login_for_format = models.DateTimeField(auto_now=True)
    def created(self):
        return self.date_joined_for_format.strftime('%B %d %Y')
    def updated(self):
        return self.last_login_for_format.strftime('%B %d %Y')

    def __str__(self):
        return self.name
    
    #def averageRating(self):
    #    reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
    #    avg = 0
    #    if reviews['average'] is not None:
    #        avg = float(reviews['average'])
    #    return avg
    #
    #def countReview(self):
    #    reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
    #    count = 0
    #    if reviews['count'] is not None:
    #        count = int(reviews['count'])
    #    return count
#
    def get_prodcut_details_url(self):
        return reverse('store:product_details', args=[self.category.slug, self.slug])
    
    #class Meta:
    #    verbose_name_plural = 'Products'
    #    ordering = ('-date_joined_for_format',)
    

cart/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

from .models import Cart, CartItem
from store.models import Product
from store.models import Variation

def _cart_id(request):
    cart = request.session.session_key
    if not cart :
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id) # get the product
    product_variation = []
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST :
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
        is_cart_item_exist = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exist:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variation.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0 :
                    item.variation.clear()
                    item.variation.add(*product_variation)
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity = 1,
                user = current_user,
            )
            if len(product_variation) > 0 :
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)
            cart_item.save()

        return redirect('cart:cart')

    # if the user is not authencated
    else:        

        if request.method == 'POST':
            for item in request.POST :
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                    print(product_variation)
                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request)) # get the cart using the cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))

        cart.save()

        is_cart_item_exist = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exist:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variation.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0 :
                    item.variation.clear()
                    item.variation.add(*product_variation)
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity = 1,
                cart=cart,
            )
            if len(product_variation) > 0 :
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)
            cart_item.save()

        return redirect('cart:cart')

def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1 :
            cart_item.quantity -= 1
            cart_item.save()
        else :
            cart_item.delete()
    except:
        pass

    return redirect('cart:cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart:cart')

def cart(request, tax=0,grand_total=0, total_price=0, quantity=0, cart_items=None):
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total_price += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = round(((2 * total_price)/100), 2)
        grand_total = total_price + tax
    except ObjectDoesNotExist:
        pass

    context={
        'total_price': total_price,
        'quantity' : quantity,
        'cart_items' : cart_items,
        'tax':tax,
        'grand_total': grand_total,
    }

    return render(request, 'home/cart/cart.html', context)

@login_required(login_url = 'accounts:login')
def checkout(request,total=0, total_price=0, quantity=0, cart_items=None):
    tax = 0.00
    handing = 0.00
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total_price += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        total = total_price + 10

    except ObjectDoesNotExist:
        pass # just ignore

    
    tax = round(((2 * total_price)/100), 2)
    grand_total = total_price + tax
    handing = 15.00
    total = float(grand_total) + handing
    
    context={
        'total_price': total_price,
        'quantity' : quantity,
        'cart_items' : cart_items,
        'tax':tax,
        'grand_total': grand_total,
    }
    return render(request, 'home/cart/checkout.html', context)

home/views.py
from django.shortcuts import render
from .models import Popular_Products, For_You
from store.models import Product
    
def home(request):
    # popular_products = Popular_Products.objects.all().filter(is_available=True)
    products = Product.objects.all().filter(is_available=True)
    for_you = Product.objects.all().filter(is_available=True, new=False)
    new_products = Product.objects.all().filter(is_available=True, new=True)


    context = {
        #'popular_products': popular_products,
        'for_you':for_you,
        'new_products': new_products,
        'products':products,
    }
    return render(request, 'home/home.html', context)

templates/home/cart/cart.html
{% extends '../../base.html' %}
{% load static %}
{% block title %}Cart | Forever{% endblock %}
{% block content %}
<br>
<br>
<section style="background:#1F0909">
    <br>
    <br>
    <br>
    <div class=container >
    {% if not cart_items %}
    <div style="font-size:18px" class="alert alert-secondary text-center" role="alert">
    Your Shopping Cart is Empty, <a href="{% url 'store:store' %}" style="font-size:18px" class="alert-link">Continue Shopping</a>.
    </div>
    {% else %}
        <div class="cartt table-responsive">
            <table class="table tablecart">
                <thead class="table-borderless">
                    <tr>
                        <th style="border-radius:20px 0 0 20px;" scope="col">Product Image</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Product Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Price	</th>
                        <th scope="col">Remove</th>
                    </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                    <tr>
                        <td><a href="{{cart_item.product.get_prodcut_details_url}}"><img style="width:100px" src="{{ cart_item.product.image.url }}"></a>
                        </td>
                        <td>
                        <a class="nameofproduct" href="{{cart_item.product.get_prodcut_details_url}}">{{cart_item.product.name}}</a>
                        
                        {% if cart_item.variation.all %}
                            {% for item in cart_item.variation.all %}
                            <br>
                            <span style="font-size:12px;color:#E2703A;">{{item.variation_category | capfirst}} : {{item.variation_value | capfirst}}</span>
                            {% endfor %}
                        {% endif %}
                        </td>
                        <td >{{cart_item.product.price}}</td>
                        <td>
                        
                        <form action="{% url 'cart:add_cart' cart_item.product.id %}" method="POST">
                            {% csrf_token %}
                            <a  href="{% url 'cart:remove_cart' cart_item.product.id cart_item.id %}" ><i class="fa fa-minus"></i></a>
                            <span >{{ cart_item.quantity }}</span>
                            {% for item in cart_item.variation.all %}
                            <input type="hidden" name={{ item.variation_category | capfirst }} value={{ item.variation_value |capfirst }}>
                            {% endfor %}
                            <button type="submit" > <i class="fa fa-plus"></i> </button>
                        </form>
                        
                        </td>
                        <td>${{cart_item.sub_total}}</td>
                        <td ><a href="{% url 'cart:remove_cart_item' cart_item.product.id cart_item.id %}" ><i onclick="return confirm('Are you really want delete this?')" class="fas fa-trash-alt delete"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
    </div>
    <br>
    <br>
    <br>
</section>
<br>
<br>
<div class="container">
    <div style="padding:15px;background:#1F0909;border-radius: 10px;box-shadow:2px 2px 10px #1F0909; " class="card" >
        <ul style="font-size:18px" class="list-group list-group-flush">
            <li style="background:#2B0D0D;color:#EEB76B" class="list-group-item">Total Price : <span style="float:right">${{ total_price }}</span></li>
            <li style="background:#2B0D0D;color:#EEB76B" class="list-group-item">Tax : <span style="float:right">${{tax}}</span></li>
            
            <li style="background:#2B0D0D;color:#FD7E14" class="list-group-item"><b>Total : <span style="float:right">${{grand_total}}</b></span></li>
        </ul>
        {% if not cart_items %}

        {% else %}
        <br>
        <br>
        <a href="{% url 'cart:checkout' %}" type="button" class="btn btn-light checkbtn">Checkout</a>
        <br>
        <button type="button" class="btn btn-dark checkbtn">Continue Shopping</button>
        <br>
        {% endif %}
    </div>
</div>
<br>
<br>
{% endblock %}

templates/home/cart/checkout.html
{% extends '../../base.html' %}
{% load static %}
{% block title %}Checkout | Forever{% endblock %}
{% block content%}
    <br>
    <!-- ##### Breadcumb Area Start ##### -->
    <div class="breadcumb_area bg-img" >
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="page-title text-center">
                        <h2>Checkout</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcumb Area End ##### -->
<br>
{% include "includes/alerts.html" %}
<form action="{% url 'orders:place_order' %}" method="POST">
{% csrf_token %}
    <!-- ##### Checkout Area Start ##### -->
    <div class="checkout_area section-padding-80">
        <div class="container">
            <div class="row">
            
                <div class="col-12 col-md-6 checkfirst">
                    <div class="checkout_details_area mt-50 clearfix">

                        <div class="cart-page-heading-title mb-30">
                            <h5>Billing Address</h5>
                        </div>

                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label for="first_name">First Name <span>*</span></label>
                                    <input name="first_name" type="text" class="form-control" id="first_name" value="" required>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="last_name">Last Name <span>*</span></label>
                                    <input name="last_name" type="text" class="form-control" id="last_name" value="" required>
                                </div>
                                <div class="col-12 mb-4">
                                    <label for="email_address">Email Address <span>*</span></label>
                                    <input name="email" type="email" class="form-control" id="email_address" value="" required>
                                </div>
                                <div class="col-12 mb-3">
                                    <label for="phone_number">Phone Number<span>*</span></label>
                                    <input name="phone" type="number" class="form-control" id="phone_number" min="0" value="" required>
                                </div>
                                <div class="col-12 mb-3">
                                    <label for="street_address">Address <span>*</span></label>
                                    <input name="address" type="text" class="form-control mb-3" id="street_address" value="" required>
                                    <input name="address2" type="text" class="form-control" id="street_address2" value="" >
                                </div>
                                <div class="col-4 mb-3">
                                    <label for="country">Country <span>*</span></label>
                                    <input name="country" type="text" class="form-control" id="country" value="" required>
                                </div>

                                <div class="col-4 mb-3">
                                    <label for="city">City <span>*</span></label>
                                    <input name="city" type="text" class="form-control" id="city" value="" required>
                                </div>
                                
                                <div class="col-4 mb-3">
                                    <label for="state">State <span>*</span></label>
                                    <input name="state" type="text" class="form-control" id="state" value="" required>
                                </div>
                                <div  class="col-12 mb-3">
                                    <label for="order-note">Order Note</label>
                                    <textarea name="order_note" style="height:200px" name="order_note" row="2" class="form-control" ></textarea>
                                </div>
                            </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-5 ml-lg-auto checksecond">
                    <br>
                    <div class="order-details-confirmation">

                        <div class="cart-page-heading">
                            <h5>Your Order</h5>
                        </div>

                        <ul class="order-details-form mb-4">
                            <li style="color:#E2703A"><span>Product</span> <span>Total</span></li>
                            {% for cart_item in cart_items %}
                            <li><span>{{ cart_item.product.name }}</span> <span>${{ cart_item.sub_total }}</span></li>
                            {% endfor %}
                            <li><span>Subtotal</span> <span>${{ total_price }}</span></li>
                            <li><span>Tax</span> <span>${{tax}}</span></li>

                            <li style="color:#FD7E14"><span>Total</span> <span>${{grand_total}}</span></li>
                        </ul>

                        <br>
                        <br>
                        <br>
                        <button type="submit" class="btn essence-btn w-100">Place Order</button>
                    </div>
                </div>
            
       
            </div>
        </div>
    </div>
</form>
    <!-- ##### Checkout Area End ##### -->
{% endblock %}