accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('', views.dashboard, name='dashboardd'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<str:user_name>/<int:order_id>/', views.order_detail, name='order_detail'),

    path('forget_password/', views.forget_password, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('reset_password/', views.reset_password, name="reset_password"),
]

cart/urls.py
from django import urls
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin-honeypot')),
    path('adminlogin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name="home"),
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='categries'),
    path('category/<slug:category_slug>/<slug:product_details_slug>/', views.product_details, name='product_details'),
    path('search/', views.search, name='search'),
    path('review/<int:product_id>/', views.review, name='review'),
]

home/models.py
from django.db import models
from store.models import Category
from django.urls import reverse

class Popular_Products(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=300, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    discount = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    image = models.ImageField(upload_to='photos/products')
    image_havor = models.ImageField(upload_to='photos/products-havor')
    stock = models.IntegerField()
    new = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)
    

    date_joined_for_format = models.DateTimeField(auto_now_add=True)
    last_login_for_format = models.DateTimeField(auto_now=True)
    def created(self):
        return self.date_joined_for_format.strftime('%B %d %Y')
    def updated(self):
        return self.last_login_for_format.strftime('%B %d %Y')

    def __str__(self):
        return self.name
    
    #def averageRating(self):
    #    reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
    #    avg = 0
    #    if reviews['average'] is not None:
    #        avg = float(reviews['average'])
    #    return avg
    #
    #def countReview(self):
    #    reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
    #    count = 0
    #    if reviews['count'] is not None:
    #        count = int(reviews['count'])
    #    return count
#
    def get_prodcut_details_url(self):
        return reverse('store:product_details', args=[self.category.slug, self.slug])
    
    #class Meta:
    #    verbose_name_plural = 'Products'
    #    ordering = ('-date_joined_for_format',)
    


class For_You(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=300, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    discount = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    image = models.ImageField(upload_to='photos/products')
    image_havor = models.ImageField(upload_to='photos/products-havor')
    stock = models.IntegerField()
    new = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)

    date_joined_for_format = models.DateTimeField(auto_now_add=True)
    last_login_for_format = models.DateTimeField(auto_now=True)
    def created(self):
        return self.date_joined_for_format.strftime('%B %d %Y')
    def updated(self):
        return self.last_login_for_format.strftime('%B %d %Y')

    def __str__(self):
        return self.name
    
    #def averageRating(self):
    #    reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
    #    avg = 0
    #    if reviews['average'] is not None:
    #        avg = float(reviews['average'])
    #    return avg
    #
    #def countReview(self):
    #    reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
    #    count = 0
    #    if reviews['count'] is not None:
    #        count = int(reviews['count'])
    #    return count
#
    def get_prodcut_details_url(self):
        return reverse('store:product_details', args=[self.category.slug, self.slug])
    
    #class Meta:
    #    verbose_name_plural = 'Products'
    #    ordering = ('-date_joined_for_format',)
    

store/models.py
from django.db import models
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=250, blank=True)
    image = models.ImageField(upload_to='categories', blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'categories'

    def get_category_slug_url(self):
        return reverse('store:categries', args=[self.slug])
# 
    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=300, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    discount = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    image = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    new = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)

    date_joined_for_format = models.DateTimeField(auto_now_add=True)
    last_login_for_format = models.DateTimeField(auto_now=True)
    def created(self):
        return self.date_joined_for_format.strftime('%B %d %Y')
    def updated(self):
        return self.last_login_for_format.strftime('%B %d %Y')

    def __str__(self):
        return self.name
    
    def averageRating(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    
    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

    def get_prodcut_details_url(self):
        return reverse('store:product_details', args=[self.category.slug, self.slug])

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choices = (
    ('color', 'color'),
    ('size', 'size'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choices)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = VariationManager()

    def __str__(self):
        return self.variation_value



class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    # user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, blank=True)
    # subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=700, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def update_at(self):
        return self.updated_at.strftime('%B %d, %Y')

    def hour_update(self):
        return self.updated_at.strftime('%H:%M:%S')

    def __str__(self):
        return self.review
        

class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None ,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_gallery')
    
    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

    def __str__(self):
        return self.product.name

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['review', 'rating']

home/views.py
from django.shortcuts import render
from .models import Popular_Products, For_You
from store.models import Product
    
def home(request):
    # popular_products = Popular_Products.objects.all().filter(is_available=True)
    products = Product.objects.all().filter(is_available=True)
    for_you = Product.objects.all().filter(is_available=True, new=False)
    new_products = Product.objects.all().filter(is_available=True, new=True)


    context = {
        #'popular_products': popular_products,
        'for_you':for_you,
        'new_products': new_products,
        'products':products,
    }
    return render(request, 'home/home.html', context)

store/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from .models import Product, Category, ProductGallery
from cart.models import CartItem
from cart.views import _cart_id
from .models import ReviewRating
from .forms import ReviewForm
from django.contrib import messages
from orders.models import OrderProduct

def store(request, category_slug=None):
    categories = None
    products = None
    
    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True).order_by('id')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        products_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        products_count = products.count()

    context = {
        'category_slug':category_slug,
        'products':paged_products ,
        'products_count': products_count,
    }

    return render(request, "home/store/store.html", context)
def product_details(request, category_slug, product_details_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_details_slug)
        
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
    except Exception as e:
        return e

    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user, product_id=single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    reviews = ReviewRating.objects.order_by('-updated_at').filter(product_id=single_product.id, status=True)
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'orderproduct':orderproduct,
        'reviews': reviews,
        'product_gallery':product_gallery,
    }
    return render(request, 'home/store/product_details.html', context)

def search(request):
    products_count = 0
    products = None
    paged_products = None
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword :
            products = Product.objects.filter(Q(description__icontains=keyword) | Q(name__icontains=keyword))
            
            products_count = products.count()
            
    
    context = {
        'products': products,
        'products_count': products_count,
    }
    return render(request, "home/store/store.html", context)

def review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id,product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you, your review updated!')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank you, your review Posted!')
                return redirect(url)

templates/home/store/product_details.html
{% extends '../../base.html' %}
{% load static %}
{% block title %}{{ single_product.name }} | Forever{% endblock %}
{% block content %}
<br>
<br>
{% include "includes/alerts.html" %}
<!-- ##### Single Product Details Area Start ##### -->
<section class=" single_product_details_area d-flex align-items-center">
    
    
    <!-- Single Product Thumb -->
    <div class="container single_product_thumb clearfix">
        <div class="product_thumbnail_slides owl-carousel mainImage">
            <img src="{{ single_product.image.url }}" alt="">
            <img src="{{single_product.image.url }}" alt="">
            
        </div>
        <div>
            <ul class="container product-slider thumb">
                <li><a href="{{ single_product.image.url }}" data-lens-image="{{single_product.image.url}}" target="mainImage"><img  src="{{single_product.image.url}}" alt="quick view"/></a></li>
                {% for i in product_gallery %}
                <li><a href="{{i.image.url}}" data-lens-image="{{i.image.url}}" target="mainImage"><img  src="{{i.image.url}}" alt="quick view" /></a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    
    <!-- Single Product Description -->
    <div class="single_product_desc clearfix">
        <div style="float:right; font-size:1.5rem" class="rating-star">
            <span style="font-size:1.5rem">( {{single_product.countReview}} Rating )</span>
            <span>
            <i class="fa fa-star{% if single_product.averageRating < 0.5 %}-o{% elif single_product.averageRating >= 0.5 and single_product.averageRating < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageRating < 1.5 %}-o{% elif single_product.averageRating >= 1.5 and single_product.averageRating < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageRating < 2.5 %}-o{% elif single_product.averageRating >= 2.5 and single_product.averageRating < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageRating < 3.5 %}-o{% elif single_product.averageRating >= 3.5 and single_product.averageRating < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageRating < 4.5 %}-o{% elif single_product.averageRating >= 4.5 and single_product.averageRating < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
            </span>
        </div>
        <h2 style="color:#FD7E14">{{ single_product.name }}</h2>
        
        <br>
        <br>
        <hr>
        <p  style=" font-size:1.8rem" class="product-price">{% if single_product.discount %}<span
                class="old-price">${{ single_product.discount }}</span>{% endif %} ${{ single_product.price }}</p>
        <hr>
        <p class="product-desc">{{ single_product.description }}</p>

        <!-- Form -->
        <form action="{% url 'cart:add_cart' single_product.id %}" class="cart-form clearfix" method="POST">
            {% csrf_token %}
            <!-- Select Box -->
            <div class="select-box d-flex mt-50 mb-30">
                {% if single_product.variation_set.colors %}
                <select name="color" id="productColor" class="mr-3">
                    <option value="" disabled selected>Select Color</option>
                    {% for x in single_product.variation_set.colors%}
                    <option value="{{x.variation_value | lower}}">Color: {{x.variation_value | capfirst}}</option>
                    {% endfor %}
                </select>
                {% endif %}
                {% if single_product.variation_set.sizes %}
                <select name="size" id="productSize">
                    <option value="" disabled selected>Select Size</option>
                    {% for x in single_product.variation_set.sizes%}
                    <option value="{{x.variation_value | lower}}">Size: {{x.variation_value | capfirst}}</option>
                    {% endfor %}
                </select>
                {% endif %}
            </div>
            <!-- Cart & Favourite Box -->
            <br>
            <br>
            <br>
            {% if single_product.stock <= 0 %}
            <div style="font-size:18px" class="alert alert-secondary text-center" role="alert">
                <b>Out Of Stock</b>
            </div>
            {% else %}
            <div class="cart-fav-box d-flex align-items-center">

                <button type="submit" name="addtocart" value="5" class="btn essence-btn w-100">Add to cart</button>
            </div>
            {% endif %}
        </form>
    </div>
</section>
<br>
<br>
<br>
<div class="comments" >
<br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-12">
        <br>
            <div >
            <h2 class="commenttitle">Write Your Review</h2>

            <br>
            <form action="{% url 'store:review' single_product.id %}" method="POST">
            {% csrf_token %}
            <h4 class="commenttitlee">Rating :</h4>
            <!-- Stars Review -->
            <div class="rate">
                <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
                <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
                <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
                <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
                <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
                <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
                <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
                <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
                <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
                <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
            </div>
            <br>
            <h4 class="commenttitlee">Review :</h4>
            <textarea name="review" row="4" ></textarea>
            <br>
            <br>
            {% if user.is_authenticated %}
                {% if orderproduct %}
                <input type="submit" value="submit your review" class="btn essence-btn float-right">
                {% else %}
                <div style="font-size:18px" class="alert alert-secondary text-center" role="alert">
                You must buy this product to review on it!
                </div>
                {% endif %}
            {% else %}
            <br>
            <div style="font-size:18px" class="alert alert-secondary text-center" role="alert">
                You must login to rate and review, <a href="{% url 'accounts:login' %}" style="font-size:18px" class="alert-link loginalert">Login</a>.
            </div>
            {% endif %}
            </form>
            </div>
        </div>
    </div>
</div>
<br>

<hr>
<br>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<section >
    <div class="container">
        <h2 class="commenttitle">Customer Rating :</h2>
        <br>
        <div class="row">
            <div class="col-md-12">
                
                {% if reviews %}
                    {% for review in reviews %}
                    <div class="media g-mb-30 media-comment">
                        <img class="d-flex g-width-50 g-height-50 rounded-circle g-mt-3 g-mr-15"
                            src="{{review.user.userprofile.profile_picture.url}}" alt="Image Description">
                        <div class="media-body u-shadow-v18 g-bg-secondary g-pa-30">
                            <div class="g-mb-15">
                                <div class="rating-star float-right">
                                    <span>
                                        <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}"
                                            aria-hidden="true"></i>
                                        <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}"
                                            aria-hidden="true"></i>
                                        <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}"
                                            aria-hidden="true"></i>
                                        <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}"
                                            aria-hidden="true"></i>
                                        <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}"
                                            aria-hidden="true"></i>
                                    </span>
                                </div>
                                <h5 class="name h5 g-color-gray-dark-v1 mb-0">{{review.user.full_name}}</h5>
                                <span class="g-color-gray-dark-v4 g-font-size-12">{{review.update_at}}</span>
                                
                            </div>
                            
                            <br>
                            <p class="comment">{{review.review}}</p>

                        </div>
                    </div>
                    {% endfor %}
                {% else %}
                <br>
                <div style="font-size:18px" class="alert alert-secondary text-center" role="alert">
                    No Customer Rating This Product Yet!
                </div>
                <br>
                {% endif %}

            </div>

        </div>
    </div>
    <br>
</section>

</div>
<!-- ##### Single Product Details Area End ##### -->
<br>
<br><br>
<br><br>
<br>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $('.thumb a').click(function(e){
            e.preventDefault();
            $('.mainImage img').attr('src', $(this).attr("href"));
            $('.mainImage a').attr('data-lens-image', $(this).attr("data-lens-image"));
        })
    })
</script>
{% endblock %}